### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by memsharded** [dimi309/gloom#1]
Hi @dimi309 

Just saw your tweet and trying it. But it seems to fail:

```bash
conan install .
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
[options]
[build_requires]
[env]

small3d/master: Not found in local cache, looking in remotes...
ERROR: Failed requirement 'small3d/master' from 'conanfile.py'
ERROR: No remote defined
```

Seems the require is a local package that should be created first from another repo?

**Comment by dimi309** [comment]
Hi @memsharded, 
Indeed, first portaudio is needed (found here https://github.com/bincrafters/community/tree/main/recipes/portaudio/19.7.0), set up as portaudio/19.7.0 locally, and small3d library (https://github.com/dimi309/small3d-conan), set up as small3d/master. Portaudio used to be on public repositories a long time ago, but it seems it is not any more. small3d is my own library, for which I have just written a recipe.

**Comment by dimi309** [comment]
I have added this information to the [README](https://github.com/dimi309/gloom-game-conan/blob/master/README.md) just now.

**Comment by dimi309** [comment]
Sorry, I have found out that there were quite a few issues with my package. I've made some builds for appveyor. The game now works on [windows, macos, and linux](https://ci.appveyor.com/project/dimi309/gloom-game-conan). Also OpenGL is now supported in addition to Vulkan.
Here's the appveyor configuration, which illustrates a successful building strategy, even though local builds should be much simpler: https://github.com/dimi309/gloom-game-conan/blob/master/appveyor.yml
Note that I'm not using the portaudio package on linux, because it crashes there. I just install portaudio from the local package manager.

**Comment by dimi309** [comment]
Sorry @memsharded , I have found out that there were quite a few issues with the build. I've configured it on appveyor and debugged it. The game now works on [windows, macos, and linux](https://ci.appveyor.com/project/dimi309/gloom-game-conan). Also OpenGL is now supported in addition to Vulkan.
Here's the appveyor configuration, which illustrates a successful building strategy, even though local builds should be much simpler: https://github.com/dimi309/gloom-game-conan/blob/master/appveyor.yml
Note that I'm not using the portaudio package on linux, because it crashes there. I just install portaudio from the local package manager.

**Comment by dimi309** [comment]
@memsharded I have simplified the [installation instructions](https://github.com/dimi309/gloom-game-conan/blob/master/README.md). Now the commands can basically be copied and pasted and the game will just run. If you have a moment by any chance, I would really be interested in finding out whether it now works on your end or not.

**Comment by dimi309** [comment]
The build procedure has been even further simplified, thanks to the [barbarian package index](https://barbarian.bfgroup.xyz/)
